# Generated by Django 3.2.16 on 2022-11-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newtravelapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
