# Generated by Django 3.2.16 on 2022-11-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtravelapp', '0002_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageofteam', models.ImageField(upload_to='pics')),
                ('nameofteam', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
